version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ECR_REPO_URI}
  build:
    commands:
      - docker build -t cloud-insights-app .
      - docker tag cloud-insights-app:latest ${ECR_REPO_URI}:latest
  post_build:
    commands:
      - docker push ${ECR_REPO_URI}:latest
      - printf '[{"name":"app","imageUri":"%s"}]' "${ECR_REPO_URI}:latest" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

